/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type LandingPage = {
  _id: string;
  _type: "landingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: Hero;
  productInfo?: ProductInfo;
  efficiencyMotor?: {
    title?: string;
    subtitle?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  accessories?: Array<{
    _key: string;
  } & Accessory>;
  gallery?: Gallery;
  color?: Color;
  testimonials?: {
    title?: string;
    items?: Array<{
      _key: string;
    } & Testimonial>;
  };
  newsletter?: Newsletter;
};

export type Newsletter = {
  _type: "newsletter";
  title?: string;
  description?: string;
  buttonLabel?: string;
};

export type Color = {
  _type: "color";
  title?: string;
  subtitle?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  colors?: Array<{
    _key: string;
  } & ColorOption>;
};

export type Gallery = {
  _type: "gallery";
  sectionTitle?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type ProductInfo = {
  _type: "productInfo";
  title?: string;
  subtitle?: string;
  points?: Array<string>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Hero = {
  _type: "hero";
  title?: string;
  titleBold?: string;
  subtitle?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  buttons?: Array<{
    _key: string;
  } & Cta>;
  stats?: Array<{
    _key: string;
  } & StatItem>;
};

export type Testimonial = {
  _type: "testimonial";
  quote?: string;
  name?: string;
  role?: string;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ColorOption = {
  _type: "colorOption";
  label?: string;
  hex?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Accessory = {
  _type: "accessory";
  name?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type StatItem = {
  _type: "statItem";
  value?: string;
  unit?: string;
  label?: string;
};

export type Cta = {
  _type: "cta";
  label?: string;
  url?: string;
};

export type NavItem = {
  _type: "navItem";
  label?: string;
  type?: "link" | "dropdown";
  url?: string;
  children?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  columns?: Array<{
    title?: string;
    links?: Array<{
      _key: string;
    } & NavItem>;
    _key: string;
  }>;
  socials?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    url?: string;
    _key: string;
  }>;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  navItems?: Array<{
    _key: string;
  } & NavItem>;
};

export type New = {
  _id: string;
  _type: "new";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = LandingPage | Newsletter | Color | Gallery | SanityImageCrop | SanityImageHotspot | ProductInfo | Hero | Testimonial | ColorOption | Accessory | StatItem | Cta | NavItem | Footer | Header | New | Slug | Post | BlockContent | Author | Category | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)][0...12]{  _id, title, slug}
export type POSTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  title, body, mainImage}
export type POST_QUERYResult = {
  title: string | null;
  body: BlockContent | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;
// Variable: LANDING_PAGE_QUERY
// Query: *[_type == "landingPage"][0]{    hero{      title,      subtitle,      image,      buttons[]{        label,        url      },      stats[]{        value,        label      }    },    productInfo{      title,      points,      image    },    efficiencyMotor{      title,      subtitle,      description,      image    },    accessories[]{      name,      description,      image    },    gallery{      sectionTitle,      images    },    colors[]{      label,      hex,      image    },    testimonials[]{      quote,      name,      role,      avatar    },    newsletter{      title,      description,      buttonLabel    }  }
export type LANDING_PAGE_QUERYResult = {
  hero: {
    title: string | null;
    subtitle: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    buttons: Array<{
      label: string | null;
      url: string | null;
    }> | null;
    stats: Array<{
      value: string | null;
      label: string | null;
    }> | null;
  } | null;
  productInfo: {
    title: string | null;
    points: Array<string> | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  efficiencyMotor: {
    title: string | null;
    subtitle: string | null;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  accessories: Array<{
    name: string | null;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }> | null;
  gallery: {
    sectionTitle: string | null;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
  } | null;
  colors: null;
  testimonials: null;
  newsletter: {
    title: string | null;
    description: string | null;
    buttonLabel: string | null;
  } | null;
} | null;
// Variable: HEADER_QUERY
// Query: *[_type == "header"][0]{    logo,    navItems[]{ label, url, type, children[] {label, url} }  }
export type HEADER_QUERYResult = {
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  navItems: Array<{
    label: string | null;
    url: string | null;
    type: "dropdown" | "link" | null;
    children: Array<{
      label: string | null;
      url: string | null;
    }> | null;
  }> | null;
} | null;
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0]{    columns[]{      title,      links[]{ label, url }    },    socials[]{ image, url },    socialLinks[]{ label, url },image  }
export type FOOTER_QUERYResult = {
  columns: Array<{
    title: string | null;
    links: Array<{
      label: string | null;
      url: string | null;
    }> | null;
  }> | null;
  socials: Array<{
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    url: string | null;
  }> | null;
  socialLinks: Array<{
    label: string | null;
    url: string | null;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;
// Variable: HERO_QUERY
// Query: *[_type == "landingPage"][0].hero{    title,    titleBold,    subtitle,    image,    buttons[]{ label, url },    stats[]{ value, unit, label }  }
export type HERO_QUERYResult = {
  title: string | null;
  titleBold: string | null;
  subtitle: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  buttons: Array<{
    label: string | null;
    url: string | null;
  }> | null;
  stats: Array<{
    value: string | null;
    unit: string | null;
    label: string | null;
  }> | null;
} | null;
// Variable: PRODUCT_INFO_QUERY
// Query: *[_type == "landingPage"][0].productInfo{    title,    subtitle,    points,    image  }
export type PRODUCT_INFO_QUERYResult = {
  title: string | null;
  subtitle: string | null;
  points: Array<string> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;
// Variable: EFFICIENCY_MOTOR_QUERY
// Query: *[_type == "landingPage"][0].efficiencyMotor{    title,    subtitle,    description,    image  }
export type EFFICIENCY_MOTOR_QUERYResult = {
  title: string | null;
  subtitle: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;
// Variable: ACCESSORIES_QUERY
// Query: *[_type == "landingPage"][0].accessories[]{    name,    description,    image  }
export type ACCESSORIES_QUERYResult = Array<{
  name: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}> | null;
// Variable: GALLERY_QUERY
// Query: *[_type == "landingPage"][0].gallery{    sectionTitle,    images  }
export type GALLERY_QUERYResult = {
  sectionTitle: string | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
} | null;
// Variable: COLORS_QUERY
// Query: *[_type == "landingPage"][0].color
export type COLORS_QUERYResult = Color | null;
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "landingPage"][0].testimonials
export type TESTIMONIALS_QUERYResult = {
  title?: string;
  items?: Array<{
    _key: string;
  } & Testimonial>;
} | null;
// Variable: NEWSLETTER_QUERY
// Query: *[_type == "landingPage"][0].newsletter{    title,    description,    buttonLabel  }
export type NEWSLETTER_QUERYResult = {
  title: string | null;
  description: string | null;
  buttonLabel: string | null;
} | null;
// Variable: FULL_PAGE_QUERY
// Query: {  "header": *[_type == "header"][0]{    logo,    navItems[]{ label, url }  },  "landingPage": *[_type == "landingPage"][0]{    hero{      title,      subtitle,      image,      buttons[]{ label, url },      stats[]{ value, label }    },    productInfo{      title,      points,      image    },    efficiencyMotor{      title,      description,      image    },    accessories[]{      name,      description,      image    },    gallery{      sectionTitle,      images    },    colors[]{      label,      hex,      image    },    testimonials[]{      quote,      name,      role,      avatar    },    newsletter{      title,      description,      buttonLabel    }  },  "footer": *[_type == "footer"][0]{    columns[]{      title,      links[]{ label, url }    },    socialLinks[]{ label, url }  }}
export type FULL_PAGE_QUERYResult = {
  header: {
    logo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    navItems: Array<{
      label: string | null;
      url: string | null;
    }> | null;
  } | null;
  landingPage: {
    hero: {
      title: string | null;
      subtitle: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      buttons: Array<{
        label: string | null;
        url: string | null;
      }> | null;
      stats: Array<{
        value: string | null;
        label: string | null;
      }> | null;
    } | null;
    productInfo: {
      title: string | null;
      points: Array<string> | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    } | null;
    efficiencyMotor: {
      title: string | null;
      description: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    } | null;
    accessories: Array<{
      name: string | null;
      description: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
    gallery: {
      sectionTitle: string | null;
      images: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }> | null;
    } | null;
    colors: null;
    testimonials: null;
    newsletter: {
      title: string | null;
      description: string | null;
      buttonLabel: string | null;
    } | null;
  } | null;
  footer: {
    columns: Array<{
      title: string | null;
      links: Array<{
        label: string | null;
        url: string | null;
      }> | null;
    }> | null;
    socialLinks: Array<{
      label: string | null;
      url: string | null;
    }> | null;
  } | null;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"post\" && defined(slug.current)][0...12]{\n  _id, title, slug\n}": POSTS_QUERYResult;
    "*[_type == \"post\" && slug.current == $slug][0]{\n  title, body, mainImage\n}": POST_QUERYResult;
    "\n  *[_type == \"landingPage\"][0]{\n    hero{\n      title,\n      subtitle,\n      image,\n      buttons[]{\n        label,\n        url\n      },\n      stats[]{\n        value,\n        label\n      }\n    },\n\n    productInfo{\n      title,\n      points,\n      image\n    },\n\n    efficiencyMotor{\n      title,\n      subtitle,\n      description,\n      image\n    },\n\n    accessories[]{\n      name,\n      description,\n      image\n    },\n\n    gallery{\n      sectionTitle,\n      images\n    },\n\n    colors[]{\n      label,\n      hex,\n      image\n    },\n\n    testimonials[]{\n      quote,\n      name,\n      role,\n      avatar\n    },\n\n    newsletter{\n      title,\n      description,\n      buttonLabel\n    }\n  }\n": LANDING_PAGE_QUERYResult;
    "\n  *[_type == \"header\"][0]{\n    logo,\n    navItems[]{ label, url, type, children[] {label, url} }\n  }\n": HEADER_QUERYResult;
    "\n  *[_type == \"footer\"][0]{\n    columns[]{\n      title,\n      links[]{ label, url }\n    },\n    socials[]{ image, url },\n    socialLinks[]{ label, url },image\n  }\n": FOOTER_QUERYResult;
    "\n  *[_type == \"landingPage\"][0].hero{\n    title,\n    titleBold,\n    subtitle,\n    image,\n    buttons[]{ label, url },\n    stats[]{ value, unit, label }\n  }\n": HERO_QUERYResult;
    "\n  *[_type == \"landingPage\"][0].productInfo{\n    title,\n    subtitle,\n    points,\n    image\n  }\n": PRODUCT_INFO_QUERYResult;
    "\n  *[_type == \"landingPage\"][0].efficiencyMotor{\n    title,\n    subtitle,\n    description,\n    image\n  }\n": EFFICIENCY_MOTOR_QUERYResult;
    "\n  *[_type == \"landingPage\"][0].accessories[]{\n    name,\n    description,\n    image\n  }\n": ACCESSORIES_QUERYResult;
    "\n  *[_type == \"landingPage\"][0].gallery{\n    sectionTitle,\n    images\n  }\n": GALLERY_QUERYResult;
    "\n  *[_type == \"landingPage\"][0].color\n\n": COLORS_QUERYResult;
    "\n *[_type == \"landingPage\"][0].testimonials\n": TESTIMONIALS_QUERYResult;
    "\n  *[_type == \"landingPage\"][0].newsletter{\n    title,\n    description,\n    buttonLabel\n  }\n": NEWSLETTER_QUERYResult;
    "\n{\n  \"header\": *[_type == \"header\"][0]{\n    logo,\n    navItems[]{ label, url }\n  },\n\n  \"landingPage\": *[_type == \"landingPage\"][0]{\n    hero{\n      title,\n      subtitle,\n      image,\n      buttons[]{ label, url },\n      stats[]{ value, label }\n    },\n    productInfo{\n      title,\n      points,\n      image\n    },\n    efficiencyMotor{\n      title,\n      description,\n      image\n    },\n    accessories[]{\n      name,\n      description,\n      image\n    },\n    gallery{\n      sectionTitle,\n      images\n    },\n    colors[]{\n      label,\n      hex,\n      image\n    },\n    testimonials[]{\n      quote,\n      name,\n      role,\n      avatar\n    },\n    newsletter{\n      title,\n      description,\n      buttonLabel\n    }\n  },\n\n  \"footer\": *[_type == \"footer\"][0]{\n    columns[]{\n      title,\n      links[]{ label, url }\n    },\n    socialLinks[]{ label, url }\n  }\n}\n": FULL_PAGE_QUERYResult;
  }
}
